[package]
name = "magnetofon"
version = "1.0.1"
description = "Magnetofon ST-8000 — High-Fidelity Audio Console & Native MilkDrop Visualizer Engine"
authors = ["Magnetofon Team"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.0", features = ["tray-icon"] }
tauri-plugin-shell = "2.0"
tauri-plugin-dialog = "2.0"
tauri-plugin-fs = "2.0"
tauri-plugin-clipboard-manager = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["stream"] }
zip = "2.2"
futures-util = "0.3"
dirs = "5.0"
lazy_static = "1.5"
